export { default as Header } from "./header/header"
export { default as About } from "./about/about"
export { default as Skills } from "./skills/skills"
export { default as Work } from "./work/work"
export { default as Footer } from "./footer/footer"